# Generated by Django 5.2.11 on 2026-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanalysis',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='urlanalysis',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
