# Generated by Django 5.2.11 on 2026-04-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_fileanalysis_confidence_imageanalysis_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=20)),
                ('input_data', models.TextField()),
                ('result', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('risk', models.CharField(max_length=20)),
                ('reasons', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
